<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MVTec.HalconDotNet" Version="25050.0.0" />
    <PackageReference Include="MVTec.HalconDotNet-Windows" Version="25050.0.0" />
  </ItemGroup>

</Project>
